# Generated by Django 3.0.6 on 2021-04-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
