# Generated by Django 3.1.7 on 2021-05-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210507_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.PositiveSmallIntegerField(default=((1, '23%'), (2, '8%'), (3, '5%'), (4, '0%'))),
        ),
    ]
