# Generated by Django 3.1.7 on 2021-05-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210507_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(choices=[(1, '23%'), (2, '8%'), (3, '5%'), (4, '0%')], decimal_places=2, max_digits=6),
        ),
    ]
