# Generated by Django 3.1.4 on 2021-04-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210419_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/img.png', upload_to='images/'),
        ),
    ]
