# Generated by Django 3.1.7 on 2021-05-07 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_auto_20210507_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users_favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
