# Generated by Django 3.2 on 2021-05-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsSpecification',
            new_name='ProductSpecification',
        ),
        migrations.RenameModel(
            old_name='ProductsSpecificationValue',
            new_name='ProductSpecificationValue',
        ),
    ]
