# Generated by Django 3.1.4 on 2021-04-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='COś o sobie'),
        ),
    ]
