# Generated by Django 2.2.6 on 2021-03-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplan',
            name='day_name',
            field=models.CharField(choices=[('MONDAY', 'Poniedziałek'), ('TUESDAY', 'Wtorek'), ('WEDNESDAY', 'Środa'), ('THURSDAY', 'Czwartek'), ('FRIDAY', 'Piątek'), ('SATURDAY', 'Sobota'), ('SUNDAY', 'Niedziela')], max_length=16),
        ),
    ]
